services:
  web:
    build: .
    image: sabidzpro/portfolio:latest
    env_file:
      - .env
    environment:
      # Next.js runtime envs (public ones prefixed with NEXT_PUBLIC_)
      - NEXT_PUBLIC_SITE_URL=${SITE_URL:-https://sabidzpro.my.id}
      - NODE_ENV=production

      # Database (Prisma Accelerate)
      - POSTGRES_PRISMA_URL=${POSTGRES_PRISMA_URL}

      # AUTH (GitHub OAuth)
      - AUTH_SECRET=${AUTH_SECRET}
      - AUTH_GITHUB_ID=${AUTH_GITHUB_ID}
      - AUTH_GITHUB_SECRET=${AUTH_GITHUB_SECRET}

      # Vercel Blob Storage (for image uploads)
      - BLOB_READ_WRITE_TOKEN=${BLOB_READ_WRITE_TOKEN}

      # Server-only envs
      - GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_KEY}

      # Admin access
      - CADDY_EMAIL=${CADDY_EMAIL}
    restart: unless-stopped
    networks:
      - webnet
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:3000 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  caddy:
    image: caddy:2-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    environment:
      - ACME_AGREE=true
      - PUID=1000
      - PGID=1000
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
    networks:
      - webnet
    depends_on:
      web:
        condition: service_healthy

networks:
  webnet:
    driver: bridge

volumes:
  caddy_data:
  caddy_config: